package com.swm.mapper;

import com.swm.entity.Account;
import com.swm.entity.Employeeinfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Account record);

    /**
     * 根据账号信息查找账号
     *
     * @param account
     * @return
     */
    Account selectByAccount(Account account);

    List<Account> selectByPageAccount(@Param("pageIndex") Integer pageIndex,
                                      @Param("pageSize") Integer pageSize,
                                      @Param("account") Account account,
                                      @Param("personList") List<Employeeinfo> personList);

    int countAll();

    int countByPageAccount(@Param("pageIndex") Integer pageIndex,
                           @Param("pageSize") Integer pageSize,
                           @Param("account") Account account,
                           @Param("personList") List<Employeeinfo> personList);

}