package com.swm.mapper;

import com.swm.entity.Accountstatus;
import java.util.List;

public interface AccountstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountstatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountstatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Accountstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountstatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Accountstatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountstatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Accountstatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountstatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Accountstatus record);
}