package com.swm.mapper;

import com.swm.entity.Employeeinfo;
import java.util.List;

public interface EmployeeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Employeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Employeeinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Employeeinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Employeeinfo record);
}