package com.swm.mapper;

import com.swm.entity.Employeesubsidy;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface EmployeesubsidyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Date workdata);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Employeesubsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Employeesubsidy selectByPrimaryKey(Date workdata);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Employeesubsidy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Employeesubsidy record);
}