package com.swm.mapper;

import com.swm.entity.Employeeinfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EmployeeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Employeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Employeeinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Employeeinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeinfo
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Employeeinfo record);
}