package com.swm.mapper;

import com.swm.entity.Employeestatus;
import java.util.List;

public interface EmployeestatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Employeestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Employeestatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Employeestatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Employeestatus record);
}