package com.swm.mapper;

import com.swm.entity.Insurancestandard;
import java.util.List;

public interface InsurancestandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurancestandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurancestandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Insurancestandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurancestandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Insurancestandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurancestandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Insurancestandard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurancestandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Insurancestandard record);
}