package com.swm.mapper;

import com.swm.entity.Promission;
import java.util.List;

public interface PromissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promission
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promission
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Promission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promission
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Promission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promission
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Promission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promission
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Promission record);
}