package com.swm.mapper;

import com.swm.entity.Salarystatus;
import java.util.List;

public interface SalarystatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Salarystatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Salarystatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Salarystatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Salarystatus record);
}