package com.swm.mapper;

import com.swm.entity.Salarystatus;
import java.util.List;

public interface SalarystatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Salarystatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Salarystatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Salarystatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salarystatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Salarystatus record);
}