package com.swm.mapper;

import com.swm.entity.Subsidytype;
import java.util.List;

public interface SubsidytypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Subsidytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Subsidytype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Subsidytype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Subsidytype record);
}