package com.swm.mapper;

import com.swm.entity.Subsidytype;
import java.util.List;

public interface SubsidytypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Subsidytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Subsidytype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Subsidytype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subsidytype
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Subsidytype record);
}