package com.swm.mapper;

import com.swm.entity.Workinghours;
import java.util.List;

public interface WorkinghoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int insert(Workinghours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    Workinghours selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    List<Workinghours> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    int updateByPrimaryKey(Workinghours record);
}