package com.swm.mapper;

import com.swm.entity.Workinghours;
import java.util.List;

public interface WorkinghoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int insert(Workinghours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    Workinghours selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    List<Workinghours> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workinghours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    int updateByPrimaryKey(Workinghours record);
}