package com.swm.entity;

public class Accountstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountstatus.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountstatus.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountstatus.id
     *
     * @return the value of accountstatus.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountstatus.id
     *
     * @param id the value for accountstatus.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountstatus.name
     *
     * @return the value of accountstatus.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountstatus.name
     *
     * @param name the value for accountstatus.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}