package com.swm.entity;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.lastLoginTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.promission
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer promission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.employeeId
     *
     * @return the value of account.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.employeeId
     *
     * @param employeeid the value for account.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.lastLoginTime
     *
     * @return the value of account.lastLoginTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.lastLoginTime
     *
     * @param lastlogintime the value for account.lastLoginTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.promission
     *
     * @return the value of account.promission
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getPromission() {
        return promission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.promission
     *
     * @param promission the value for account.promission
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPromission(Integer promission) {
        this.promission = promission;
    }
}