package com.swm.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.leaderId
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer leaderid;

    private Employeeinfo leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.createTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.introduction
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.leaderId
     *
     * @return the value of department.leaderId
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getLeaderid() {
        return leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.leaderId
     *
     * @param leaderid the value for department.leaderId
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setLeaderid(Integer leaderid) {
        this.leaderid = leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.remark
     *
     * @return the value of department.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.remark
     *
     * @param remark the value for department.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.createTime
     *
     * @return the value of department.createTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.createTime
     *
     * @param createtime the value for department.createTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.introduction
     *
     * @return the value of department.introduction
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.introduction
     *
     * @param introduction the value for department.introduction
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public Employeeinfo getLeader() {
        return leader;
    }

    public void setLeader(Employeeinfo leader) {
        this.leader = leader;
    }
}