package com.swm.entity;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.leaderId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer leaderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.leaderId
     *
     * @return the value of department.leaderId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getLeaderid() {
        return leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.leaderId
     *
     * @param leaderid the value for department.leaderId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setLeaderid(Integer leaderid) {
        this.leaderid = leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.remark
     *
     * @return the value of department.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.remark
     *
     * @param remark the value for department.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}