package com.swm.entity;

import java.util.Date;

public class Employeesubsidy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeesubsidy.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date workdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeesubsidy.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeesubsidy.subsidyId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer subsidyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeesubsidy.subsidyAmount
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer subsidyamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeesubsidy.workData
     *
     * @return the value of employeesubsidy.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getWorkdata() {
        return workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeesubsidy.workData
     *
     * @param workdata the value for employeesubsidy.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setWorkdata(Date workdata) {
        this.workdata = workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeesubsidy.employeeId
     *
     * @return the value of employeesubsidy.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeesubsidy.employeeId
     *
     * @param employeeid the value for employeesubsidy.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeesubsidy.subsidyId
     *
     * @return the value of employeesubsidy.subsidyId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getSubsidyid() {
        return subsidyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeesubsidy.subsidyId
     *
     * @param subsidyid the value for employeesubsidy.subsidyId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setSubsidyid(Integer subsidyid) {
        this.subsidyid = subsidyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeesubsidy.subsidyAmount
     *
     * @return the value of employeesubsidy.subsidyAmount
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getSubsidyamount() {
        return subsidyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeesubsidy.subsidyAmount
     *
     * @param subsidyamount the value for employeesubsidy.subsidyAmount
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setSubsidyamount(Integer subsidyamount) {
        this.subsidyamount = subsidyamount;
    }
}