package com.swm.entity;

import java.util.Date;

public class Employeeinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.sex
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.brithday
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.telPhone
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.email
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.address
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.identificationId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String identificationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.education
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.school
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.profession
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.nationality
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.politicalStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String politicalstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.entryTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.expireDate
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date expiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.departmentId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.positionId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer positionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double basesalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double positionsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.subsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double subsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.insuranceStandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer insurancestandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeinfo.employeeStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer employeestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.id
     *
     * @return the value of employeeinfo.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.id
     *
     * @param id the value for employeeinfo.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.name
     *
     * @return the value of employeeinfo.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.name
     *
     * @param name the value for employeeinfo.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.sex
     *
     * @return the value of employeeinfo.sex
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.sex
     *
     * @param sex the value for employeeinfo.sex
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.brithday
     *
     * @return the value of employeeinfo.brithday
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.brithday
     *
     * @param brithday the value for employeeinfo.brithday
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.telPhone
     *
     * @return the value of employeeinfo.telPhone
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.telPhone
     *
     * @param telphone the value for employeeinfo.telPhone
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.email
     *
     * @return the value of employeeinfo.email
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.email
     *
     * @param email the value for employeeinfo.email
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.address
     *
     * @return the value of employeeinfo.address
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.address
     *
     * @param address the value for employeeinfo.address
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.identificationId
     *
     * @return the value of employeeinfo.identificationId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getIdentificationid() {
        return identificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.identificationId
     *
     * @param identificationid the value for employeeinfo.identificationId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setIdentificationid(String identificationid) {
        this.identificationid = identificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.education
     *
     * @return the value of employeeinfo.education
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.education
     *
     * @param education the value for employeeinfo.education
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.school
     *
     * @return the value of employeeinfo.school
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.school
     *
     * @param school the value for employeeinfo.school
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.profession
     *
     * @return the value of employeeinfo.profession
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.profession
     *
     * @param profession the value for employeeinfo.profession
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.nationality
     *
     * @return the value of employeeinfo.nationality
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.nationality
     *
     * @param nationality the value for employeeinfo.nationality
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.politicalStatus
     *
     * @return the value of employeeinfo.politicalStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getPoliticalstatus() {
        return politicalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.politicalStatus
     *
     * @param politicalstatus the value for employeeinfo.politicalStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPoliticalstatus(String politicalstatus) {
        this.politicalstatus = politicalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.entryTime
     *
     * @return the value of employeeinfo.entryTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.entryTime
     *
     * @param entrytime the value for employeeinfo.entryTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.expireDate
     *
     * @return the value of employeeinfo.expireDate
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.expireDate
     *
     * @param expiredate the value for employeeinfo.expireDate
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.departmentId
     *
     * @return the value of employeeinfo.departmentId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.departmentId
     *
     * @param departmentid the value for employeeinfo.departmentId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.positionId
     *
     * @return the value of employeeinfo.positionId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.positionId
     *
     * @param positionid the value for employeeinfo.positionId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.baseSalary
     *
     * @return the value of employeeinfo.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getBasesalary() {
        return basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.baseSalary
     *
     * @param basesalary the value for employeeinfo.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setBasesalary(Double basesalary) {
        this.basesalary = basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.positionSalary
     *
     * @return the value of employeeinfo.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getPositionsalary() {
        return positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.positionSalary
     *
     * @param positionsalary the value for employeeinfo.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPositionsalary(Double positionsalary) {
        this.positionsalary = positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.subsidy
     *
     * @return the value of employeeinfo.subsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getSubsidy() {
        return subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.subsidy
     *
     * @param subsidy the value for employeeinfo.subsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setSubsidy(Double subsidy) {
        this.subsidy = subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.insuranceStandard
     *
     * @return the value of employeeinfo.insuranceStandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getInsurancestandard() {
        return insurancestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.insuranceStandard
     *
     * @param insurancestandard the value for employeeinfo.insuranceStandard
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setInsurancestandard(Integer insurancestandard) {
        this.insurancestandard = insurancestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeinfo.employeeStatus
     *
     * @return the value of employeeinfo.employeeStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getEmployeestatus() {
        return employeestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeinfo.employeeStatus
     *
     * @param employeestatus the value for employeeinfo.employeeStatus
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEmployeestatus(Integer employeestatus) {
        this.employeestatus = employeestatus;
    }
}