package com.swm.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class EmpSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.workData
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Date workdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.employeeId
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer employeeId;

    private EmployeeinfoEntity employeeEntity;

    private Department department;

    private Position position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.baseSalary
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Double basesalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.positionSalary
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Double positionsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.baseSubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer basesubsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.otherSubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Double total;

    private Double workHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.tax
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Double tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.insurance
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Double insurance; // 加班工资

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.status
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.approver
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer approver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.payTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Date paytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.workData
     *
     * @return the value of salary.workData
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Date getWorkdata() {
        return workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.workData
     *
     * @param workdata the value for salary.workData
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setWorkdata(Date workdata) {
        this.workdata = workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.employeeId
     *
     * @return the value of salary.employeeId
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.employeeId
     *
     * @param employeeId the value for salary.employeeId
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.baseSalary
     *
     * @return the value of salary.baseSalary
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Double getBasesalary() {
        return basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.baseSalary
     *
     * @param basesalary the value for salary.baseSalary
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setBasesalary(Double basesalary) {
        this.basesalary = basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.positionSalary
     *
     * @return the value of salary.positionSalary
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Double getPositionsalary() {
        return positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.positionSalary
     *
     * @param positionsalary the value for salary.positionSalary
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setPositionsalary(Double positionsalary) {
        this.positionsalary = positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.baseSubsidy
     *
     * @return the value of salary.baseSubsidy
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getBasesubsidy() {
        return basesubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.baseSubsidy
     *
     * @param basesubsidy the value for salary.baseSubsidy
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setBasesubsidy(Integer basesubsidy) {
        this.basesubsidy = basesubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.otherSubsidy
     *
     * @return the value of salary.otherSubsidy
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.tax
     *
     * @return the value of salary.tax
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Double getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.tax
     *
     * @param tax the value for salary.tax
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setTax(Double tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.insurance
     *
     * @return the value of salary.insurance
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Double getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.insurance
     *
     * @param insurance the value for salary.insurance
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setInsurance(Double insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.status
     *
     * @return the value of salary.status
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.status
     *
     * @param status the value for salary.status
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.approver
     *
     * @return the value of salary.approver
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getApprover() {
        return approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.approver
     *
     * @param approver the value for salary.approver
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setApprover(Integer approver) {
        this.approver = approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.payTime
     *
     * @return the value of salary.payTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.payTime
     *
     * @param paytime the value for salary.payTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }


    public EmployeeinfoEntity getEmployeeEntity() {
        return employeeEntity;
    }

    public void setEmployeeEntity(EmployeeinfoEntity employeeEntity) {
        this.employeeEntity = employeeEntity;
    }

    public Double getWorkHours() {
        return workHours;
    }

    public void setWorkHours(Double workHours) {
        this.workHours = workHours;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmpSalary)) return false;

        EmpSalary empSalary = (EmpSalary) o;

        if (getWorkdata() != null ? !getWorkdata().equals(empSalary.getWorkdata()) : empSalary.getWorkdata() != null)
            return false;
        return getEmployeeId() != null ? getEmployeeId().equals(empSalary.getEmployeeId()) : empSalary.getEmployeeId() == null;
    }

    @Override
    public int hashCode() {
        int result = getWorkdata() != null ? getWorkdata().hashCode() : 0;
        result = 31 * result + (getEmployeeId() != null ? getEmployeeId().hashCode() : 0);
        return result;
    }
}