package com.swm.entity;

import org.springframework.stereotype.Component;

@Component
public class Insurancestandard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.pension
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer pension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.medical
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer medical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.unemployment
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer unemployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.injury
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer injury;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.maternity
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer maternity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurancestandard.housing
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer housing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.id
     *
     * @return the value of insurancestandard.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.id
     *
     * @param id the value for insurancestandard.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.name
     *
     * @return the value of insurancestandard.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.name
     *
     * @param name the value for insurancestandard.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.pension
     *
     * @return the value of insurancestandard.pension
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getPension() {
        return pension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.pension
     *
     * @param pension the value for insurancestandard.pension
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setPension(Integer pension) {
        this.pension = pension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.medical
     *
     * @return the value of insurancestandard.medical
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.medical
     *
     * @param medical the value for insurancestandard.medical
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setMedical(Integer medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.unemployment
     *
     * @return the value of insurancestandard.unemployment
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getUnemployment() {
        return unemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.unemployment
     *
     * @param unemployment the value for insurancestandard.unemployment
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setUnemployment(Integer unemployment) {
        this.unemployment = unemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.injury
     *
     * @return the value of insurancestandard.injury
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getInjury() {
        return injury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.injury
     *
     * @param injury the value for insurancestandard.injury
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setInjury(Integer injury) {
        this.injury = injury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.maternity
     *
     * @return the value of insurancestandard.maternity
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getMaternity() {
        return maternity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.maternity
     *
     * @param maternity the value for insurancestandard.maternity
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setMaternity(Integer maternity) {
        this.maternity = maternity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurancestandard.housing
     *
     * @return the value of insurancestandard.housing
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getHousing() {
        return housing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurancestandard.housing
     *
     * @param housing the value for insurancestandard.housing
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setHousing(Integer housing) {
        this.housing = housing;
    }
}