package com.swm.entity;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.name
     *
     * @return the value of position.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.name
     *
     * @param name the value for position.name
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.remark
     *
     * @return the value of position.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.remark
     *
     * @param remark the value for position.remark
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}