package com.swm.entity;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.duty
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.required
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String required;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.name
     *
     * @return the value of position.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.name
     *
     * @param name the value for position.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.remark
     *
     * @return the value of position.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.remark
     *
     * @param remark the value for position.remark
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.duty
     *
     * @return the value of position.duty
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.duty
     *
     * @param duty the value for position.duty
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.required
     *
     * @return the value of position.required
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.required
     *
     * @param required the value for position.required
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setRequired(String required) {
        this.required = required;
    }
}