package com.swm.entity;

import java.util.Date;

public class Salary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date workdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double basesalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double positionsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.baseSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer basesubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.otherSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer othersubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.tax
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.insurance
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Double insurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.approver
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Integer approver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.payTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    private Date paytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.workData
     *
     * @return the value of salary.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getWorkdata() {
        return workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.workData
     *
     * @param workdata the value for salary.workData
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setWorkdata(Date workdata) {
        this.workdata = workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.employeeId
     *
     * @return the value of salary.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.employeeId
     *
     * @param employeeid the value for salary.employeeId
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.baseSalary
     *
     * @return the value of salary.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getBasesalary() {
        return basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.baseSalary
     *
     * @param basesalary the value for salary.baseSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setBasesalary(Double basesalary) {
        this.basesalary = basesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.positionSalary
     *
     * @return the value of salary.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getPositionsalary() {
        return positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.positionSalary
     *
     * @param positionsalary the value for salary.positionSalary
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPositionsalary(Double positionsalary) {
        this.positionsalary = positionsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.baseSubsidy
     *
     * @return the value of salary.baseSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getBasesubsidy() {
        return basesubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.baseSubsidy
     *
     * @param basesubsidy the value for salary.baseSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setBasesubsidy(Integer basesubsidy) {
        this.basesubsidy = basesubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.otherSubsidy
     *
     * @return the value of salary.otherSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getOthersubsidy() {
        return othersubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.otherSubsidy
     *
     * @param othersubsidy the value for salary.otherSubsidy
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setOthersubsidy(Integer othersubsidy) {
        this.othersubsidy = othersubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.tax
     *
     * @return the value of salary.tax
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.tax
     *
     * @param tax the value for salary.tax
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setTax(Double tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.insurance
     *
     * @return the value of salary.insurance
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Double getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.insurance
     *
     * @param insurance the value for salary.insurance
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setInsurance(Double insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.status
     *
     * @return the value of salary.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.status
     *
     * @param status the value for salary.status
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.approver
     *
     * @return the value of salary.approver
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Integer getApprover() {
        return approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.approver
     *
     * @param approver the value for salary.approver
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setApprover(Integer approver) {
        this.approver = approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.payTime
     *
     * @return the value of salary.payTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.payTime
     *
     * @param paytime the value for salary.payTime
     *
     * @mbg.generated Mon Dec 04 16:14:32 CST 2017
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }
}