package com.swm.entity;

import java.util.Date;

public class Salarystatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salarystatus.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salarystatus.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salarystatus.addTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salarystatus.id
     *
     * @return the value of salarystatus.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salarystatus.id
     *
     * @param id the value for salarystatus.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salarystatus.name
     *
     * @return the value of salarystatus.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salarystatus.name
     *
     * @param name the value for salarystatus.name
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salarystatus.addTime
     *
     * @return the value of salarystatus.addTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salarystatus.addTime
     *
     * @param addtime the value for salarystatus.addTime
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}