package com.swm.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class Workinghours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.workData
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Date workdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.workHours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer workhours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.overTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    private Integer overtime;
    private Integer empId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.id
     *
     * @return the value of workinghours.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.id
     *
     * @param id the value for workinghours.id
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.workData
     *
     * @return the value of workinghours.workData
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Date getWorkdata() {
        return workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.workData
     *
     * @param workdata the value for workinghours.workData
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setWorkdata(Date workdata) {
        this.workdata = workdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.workHours
     *
     * @return the value of workinghours.workHours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getWorkhours() {
        return workhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.workHours
     *
     * @param workhours the value for workinghours.workHours
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setWorkhours(Integer workhours) {
        this.workhours = workhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.overTime
     *
     * @return the value of workinghours.overTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public Integer getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.overTime
     *
     * @param overtime the value for workinghours.overTime
     *
     * @mbg.generated Thu Jan 18 20:59:16 CST 2018
     */
    public void setOvertime(Integer overtime) {
        this.overtime = overtime;
    }

    public Integer getEmpId() {
        return empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
}